apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-deployment
  labels:
    app: k8s-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-docker
  template:
    metadata:
      labels:
        app: k8s-docker
    spec:
      containers:
      - name: k8s-docker
        image: gowthaman02/sellmanagement
        ports:
        - containerPort: 8080